// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poxnbyaoueuplfygqiud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBveG5ieWFvdWV1cGxmeWdxaXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTExMDgsImV4cCI6MjA2MzkyNzEwOH0.fahyaE47aTMT1OrNzRZnRbuxMUKPpBZNdoOelbbpHng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);